spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    username: sa
    data-password:
    url: jdbc:h2:mem:testdb
#  jpa:
#    show-sql: true
springdoc:
  writer-with-default-pretty-printer: true
---
spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    username: sa
    data-password:
    url: jdbc:h2:mem:testdb
#  jpa:
#    show-sql: true
springdoc:
  writer-with-default-pretty-printer: true